---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: coucou
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      # - git:
      #     requeueAfterSeconds: 10
      #     repoURL: https://github.com/johnvox/sandbox
      #     revision: argocd
      #     directories:
      #     - path: charts/*
      #     - path: charts/*.disabled
      #       exclude: true
      #     pathParamPrefix: chart
      - list:
          elements:
          - chart.path.basename: argocd
      - merge:
          mergeKeys:
          - kind
          generators:
          - list:
              elements:
              - kind: argocd-override
          - git:
              requeueAfterSeconds: 10
              repoURL: https://github.com/johnvox/sandbox 
              revision: argocd
              files:
              - path: apps/*/.argocd.yaml
              values:
                kind: argocd-override
  templatePatch: |
    {{- $app := . | dig (.chart.path.basename) (dict) -}}
    metadata:
      labels:
        test: {{ . | toJson | b64enc }}
  #       {{ $app | dig "labels" (dict) | toJson }}
  #     annotations:
  #       {{ $app | dig "annotations" (dict) | toJson }}
  #   spec:
  #     info:
  #       {{ $app | dig "spec" "info" (list) | toJson }}
  #     syncPolicy:
  #       {{ $app | dig "spec" "syncPolicy" (dict) | toJson }}
  #     ignoreDifferences:
  #       {{ $app | dig "spec" "ignoreDifferences" (list) | toJson }}
  template:
    metadata:
      name: 'coucou-{{.chart.path.basename}}'
      annotations:
        monitoring/disable-alerting: "true"
    spec:
      project: default
      sources:
      - repoURL: https://github.com/johnvox/sandbox
        targetRevision: argocd
        path: '{{ .chart.path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'default'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=false
        managedNamespaceMetadata:
          labels:        
            policy/replace-registry: "true"
            ca.bundle/inject: "true"
          annotations: {}